language: python

install:
    - pip install tox
    - pip install coveralls

script: tox

after_success: coveralls

env:
    - TOXENV=py27-django1.6
    - TOXENV=py33-django1.6
    - TOXENV=py34-django1.6
    - TOXENV=coverage
